// pages/_document.tsx

//Este archivo es el lugar adecuado para definir la estructura global del HTML
// (incluyendo <html>, <head>, y <body>). Esto se renderiza una vez en el servidor 
// y es consistente para todas las páginas.

// pages/_document.tsx
// pages/_document.tsx
import Document, { Html, Head, Main, NextScript } from 'next/document';

class MyDocument extends Document {
  render() {
    return (
      <Html lang="en">
        <Head>
          <meta charSet="UTF-8" />
          <meta name="viewport" content="width=device-width, initial-scale=1.0" />
          <link rel="stylesheet" href="/globals.css" />
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
        </Head>
        <body>
          <Main />
          <NextScript />
        </body>
      </Html>
    );
  }
}

export default MyDocument;


